[firebase]
api_key = "AIzaSyBa4-3q9biWgxXyDB7C0sJi_imye2_f6lM"
auth_domain = "forexai-dashboard-4413b.firebaseapp.com"
project_id = "forexai-dashboard-4413b"
storage_bucket = "forexai-dashboard-4413b.firebasestorage.app"
messaging_sender_id = "781579143280"
app_id = "1:781579143280:web:012fa56ee10f07d4d10cb5"
measurement_id = "G-GLVVJWRVFN"

[telegram]
bot_token = "8230694522:AAGtK_pPK_g7nIyt1y7F62CsgGDMFTcZ6cU"
chat_id = "5389102928"